
# Setup
title:            Black Jack
tagline:          'A configurable iOS card game'

author:
  name:           'Sameer Totey'
  url:            http://www.sameertotey.com

paginate:         5

github:
  repo:           https://github.com/BlackJack


#
# This file contains configuration flags for the Jekyll-now themes/templates
#

# Name of your site (displayed in the header)
name: Black Jack

# Short bio or description (displayed in the header)
description: A configurable iOS card game 

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://s.gravatar.com/avatar/e9ade3fc54fffb4d219330e62e94554a?s=80

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: sameertotey@gmail.com
  facebook: sameertotey
  flickr:
  github: sameertotey
  instagram:
  linkedin: sameertotey
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: sameertotey
  stackoverflow: users/3435374/user3435374
  youtube: # channel/<your_long_string> or user/<user-name>

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: sameertoteyblog

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-60982010-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://www.sameertotey.com/BlackJack

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: /BlackJack

#
# !! You don't need to change any of the configuration flags below !!
#

# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# The release of Jekyll Now that you're using
version: v2.4.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
